### ISSUE TITLE
Error when compiling with "load" configuration on Windows

### ISSUE THREAD

**Issue by GabyForceQ** [MoritzMaxeiner/llvm-d#25]
C:\Users\knopp\AppData\Local\dub\packages\llvm-d-2.4.0\llvm-d\source\llvm\functions\load.d-mixin-126(126,20): Error: variable `llvm.functions.load.core` conflicts with import llvm.functions.load.core at C:\Users\knopp\AppData\Local\dub\packages\llvm-d-2.4.0\llvm-d\source\llvm\functions\load.d(33,12)
C:\Users\knopp\AppData\Local\dub\packages\llvm-d-2.4.0\llvm-d\source\llvm\functions\load.d-mixin-126(126,12): Error: package core has no type.

**Comment by GabyForceQ** [comment]
I use DMD 2.082.1

**Comment by MoritzMaxeiner** [comment]
Could you please provide steps to reproduce (e.g. what command did you execute to get this error)?

**Comment by MoritzMaxeiner** [comment]
This should be fixed by https://github.com/MoritzMaxeiner/llvm-d/commit/79ff8f9f4b73f7830121cd60860bac53c1616549, if not, please reopen with more information.
